
#pragma once

namespace http {
	enum StatusCode {
		OK = 200,
		CREATED = 201,
		NO_CONTENT = 204,
		BAD_REQUEST = 400,
		FORBIDDEN = 403,
		NOT_FOUND = 404,
		METHOD_NOT_ALLOWED,
		PAYLOAD_TOO_LARGE = 413,
		INTERNAL_SERVER_ERROR = 500,
		NOT_IMPLEMENTED = 501,
		VERSION_NOT_SUPPORTED = 505,
		BAD_GATEWAY = 502,
		GATEWAY_TIMEOUT = 504,
	};

	enum {
		MIN_HTTP_STATUS_CODE = 100,
		MAX_HTTP_STATUS_CODE = 599,
	};
}
