
server {
	listen 3000;
	root ./var/www/;
	session_enabled on;
	session_store  cookies;
	session_timeout 1800;
	session_cookie_name TEST;

	location /counter {
		allowed_methods GET;
		autoindex off;
	}

	location /login {
		allowed_methods POST;
		client_max_body_size 100;
	}

	location /profile {
		allowed_methods GET;
		autoindex off;
	}

	location /logout {
		allowed_methods DELETE;
	}

	location / {
		root ./tests/cookies;
		index login.html;
		allowed_methods GET;
	}
}

