
server {
    listen 0.0.0.0:8080;
    server_name localhost something.com;
    root ./var/www/;
    index index.html index.htm;
    client_max_body_size 100;
    error_page 404 ./var/www/error_pages/404.html;
    error_page 403 ./var/www/error_pages/403.html;
    session_enabled on;
    session_cookie_name WEBSESSID;
    session_timeout 3600;
    session_store ./sessions;

    location / {
        root  ./var/www/;
        index index.html index.htm;
        allowed_methods GET;
        autoindex on;
        upload_enable on;
        upload_path ./var/www/uploads;
        cgi_pass .php /usr/bin/php-cgi;
        cgi_pass .py /usr/bin/python3;
        cgi_pass .bla ./var/www/cgi-bin/cgi_test;
        cgi_dir cgi-bin;
        cgi_timeout 5;
    }

    location /images {
        root ./var/www/assets/images/;

        autoindex off;
    }

    location /post_body {
        root ./var/www/;
        upload_enable on;
        client_max_body_size 100;
        upload_path ./var/www/uploads/;
    }

    location /browser {
        root ./tests/browser/;
        index index.html;
        allowed_methods GET POST DELETE;
    }

    location /directory {
        root ./YoupiBanane/;
        allowed_methods GET POST DELETE;
        index youpi.bad_extension nop/youpi.bad_extension;
        autoindex off;
    }
}


server {
    listen 0.0.0.0:8080;
    server_name localhost something.com;
    root ./var/www/;
    index index.html index.htm;
    client_max_body_size 100;
    error_page 404 ./var/www/error_pages/404.html;
    error_page 403 ./var/www/error_pages/403.html;
    session_enabled on;
    session_cookie_name WEBSESSID;
    session_timeout 3600;
    session_store ./sessions;

    location / {
        root  ./var/www/;
        index index.html index.htm;
        allowed_methods GET;
        autoindex on;
        upload_enable on;
        upload_path ./var/www/uploads;
        cgi_pass .php /usr/bin/php-cgi;
        cgi_pass .py /usr/bin/python3;
        cgi_pass .bla ./var/www/cgi-bin/cgi_test;
        cgi_dir cgi-bin;
        cgi_timeout 5;
    }

    location /images {
        root ./var/www/assets/images/;

        autoindex off;
    }

    location /post_body {
        root ./var/www/;
        upload_enable on;
        client_max_body_size 100;
        upload_path ./var/www/uploads/;
    }

    location /browser {
        root ./tests/browser/;
        index index.html;
        allowed_methods GET POST DELETE;
    }

    location /directory {
        root ./YoupiBanane/;
        allowed_methods GET POST DELETE;
        index youpi.bad_extension nop/youpi.bad_extension;
        autoindex off;
    }
}

