#y try
server {
    listen 8080;
    server_name localhost;
    root ./www;
    index index.html index.htm;

    location / {
        root ./www;
        allowed_methods GET POST;
    }
    #rt ertr
    location /images {
        root ./images;
        allowed_methods GET;
    }
}
